flowchart TD
  A[Серверное приложение] --> B[src]
  B --> C[config]
  C -.-> C1["Конфигурационные файлы и настройки"]
  B --> D[database]
  D -.-> D1["Логика работы с базой данных"]
  B --> E[models]
  E -.-> E1["Определения моделей данных"]
  B --> F[routes]
  F -.-> F1["Определение маршрутов API"]
  B --> G[uploads]
  G -.-> G1["Обработка и хранение загружаемых файлов"]
  B --> H[utils]
  H -.-> H1["Вспомогательные утилиты и парсеры"]
  B --> I[index.ts]
  I -.-> I1["Точка входа сервера, инициализация и запуск приложения"]